# 47장 에러 처리

## 47.1 에러 처리의 필요성 

에러는 언제나 발생하고 에러에 적절히 대처하지 않으면 프로그램은 강제 종료됨.

```jsx
console.log('[Start]');

foo(); // ReferenceError: foo is not defined
// 발생한 에러를 방치하면 프로그램은 강제 종료 됨

// 에러에 의해 프로그램이 강제 종료되어 아래 코드는 실행되지 않음
console.log('[End]');
```

try...catch문을 사용해 발생한 에러에 적절하게 대응하면 강제 종료되지 않고 계속해서 코드를 실행 할 수 있음.
```jsx
console.log('[Start]');

try{
    foo();
}catch (error) {
    console.log('[에러 발생]', error);
    // [에러 발생] ReferenceError: foo is not defined
}

// 발생한 에러에 적절한 대응을 하면 강제 종료 되지 않음
console.log('[End]')
```

직접적으로 에러를 발생하지는 않는 예외적인 상황이 발생할 수도 있어 적절히 대응해 에러를 방지해야 함.
```jsx
// DOM에 button 요소가 존재하지 않으면 querySelector 메서드는 에러를 발생시키지 않고 null 반환
const $button = document.querySelector('button'); // null

$button.classList.add('disabled');
// TypeError: Cannot read property 'classList' of null
```

위 예제 querySelector 메서드는 인수로 전달한 문자열이 CSS 선택자 문법에 맞지 않는 경우 에러를 발생 시킴.
```jsx
const $elem = document.querySelected('#1');
// DOMException: Failed to execute 'querySelector' on 'Document': '#1' is not a valid selector
```
하지만 CSS 선택자 문자열로 요소 노드를 찾을 수 없는 경우 에러를 발생시키지 않고 null을 반환함. 이때 if문으로 querySelector 메서드의 반환값을 확인하거나 단축 평가 또는 옵셔널 체이닝 연산자 ?. 를 사용하지 않으면 에러로 이어질 가능성이 큼.

```jsx
const $button = document.querySelector('button'); // null
$button?.classList.add('disabled');
```

## 47.2 try...catch...finally 문
```jsx
try{
    // 실행할 코드(에러 발생 가능성이 있는 코드) 
} catch(err) {
    // try 코드 블록에서 에러 발생시 이 코드 블록의 코드가 실행
    // err에는 try 코드 블럭에서 발생한 Error 객체가 전달
} finally {
    // 에러 발생과 상관없이 반드시 한 번 실행
}
```


```jsx
console.log('[Start]');

try{
    foo();
} catch (err) {
    console.log(err); // ReferenceError: foo is not defined
} finally {
    console.log('finally');
}

// try... catch... finally 문으로 에러를 처리하면 프로그램이 강제로 종료되지 않음
console.log('[End]')

```

## 47.3 Error 객체

Error 생성자 함수는 에러 객체를 생성. 에러를 상세히 설명하는 에러 메세지를 인수로 전달 할 수 있음.
```jsx
const error = new Error('잉잉 나는 틀렸어');
```

Error 생성자 함수가 생성한 에러 객체는 message 프로퍼티와 stack 프로퍼티를 갖음. 
- message: 생성자 함수에 인수로 전달한 에러 메세지
- stack: 에러를 발생시킨 콜 스택의 호출 정보 문자열로 디버깅에 사용

**Error 생성자 함수 종류**
| 생성자 함수    | 인스턴스                                                                       |
| -------------- | ------------------------------------------------------------------------------ |
| Error          | 일반적 에러 객체                                                               |
| SyntaxError    | 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체                |
| ReferenceError | 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체                         |
| TypeError      | 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체         |
| RangeError     | 숫자값의 허용 범위를 벗어났을 떄 발생하는 에러 객체                            |
| URIError       | encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체 |
| EvalError      | eval 함수에서 발생한는 에러 객체                                               |

```jsx
1 @ 1; // SyntaxError: Invalid or unexpected token
foo(); // ReferenceError: foo is not defined
null.foo; // TypeError: Cannot read property 'foo' of null
new Array(-1); // RangeError: Invalid array length
decodeURIComponent('%'); // URIError: URI malformed
```

## 47.4 throw 문
throw 문의 표현식은 어떤 값이라도 상관없지만 일반적으로 에러 객체를 지정함. throw 문으로 에러 객체를 던져 에러 발생시킴.
```jsx
try{
    throw new Error('something wrong')
} catch (error) {
    console.log(error);
}
```

**에러 발생시키기** 
```jsx
const repeat = (n, f)=>{
    if (typeof f !== 'function') throw new TypeError('f nust be a function');

    // ...
}
```

## 47.5 에러의 전파
에러는 호출자 방향으로 전파함. 즉 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 직전에 푸시된 실행 컨택스트 방향)으로 전파됨.

```jsx
const foo = () => {
    throw Error('foo에서 발생한 에러'); // (4)
}

const bar = () => {
    foo(); // (3)
}

const baz = () => {
    bar(); // (2)
}

try {
    baz(); // (1)
} catch (err) {
    console.error(err);
}
```
(1)에서 baz를 호출하면 (2)에서 bar 함수가 호출되고 (3)에서 foo 함수가 호출되고 foo 함수는 (4)에서 에러를 throw 함. 이때 foo 함수가 throw한 에러는 다음과 같이 호출자에게 전파되어 전역에서 캐치 됨.

![image](https://github.com/dev-hamster/study-js-deep-dive/assets/123740296/17f9267a-bddb-419d-b091-3c41a70ae343)


throw된 에러를 캐치하지 않으면 호출자 방향으로 전파됨. 이때 throw된 에러를 캐치하여 적절히 대응시 코드의 실행 흐름을 복구할 수 있음.

주의할 점:
- 비동기 함수인 setTimeout, 프로미스 후속 처리 메서드의 콜백 함수는 호출자가 없음.
